version: 2

368_config: &368_config
  docker:
    - image: circleci/python:3.6.8

jobs:
  build:
    <<: *368_config

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo pip install awscli

  deploy:
    <<: *368_config
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: aws s3 src/* s3://document-browser --recursive

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  
            tags:
              only: /.*/
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master